<?php

/**
 * @file
 * Contains hy_esb.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hy_esb_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hy_esb module.
    case 'help.page.hy_esb':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrations to ESB') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_webform_element_alter().
 *
 * @param array              $element
 * @param FormStateInterface $form_state
 * @param array              $context
 */
function hy_esb_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  // TODO set form element for efecte_id
  // and then create validation class for it
  // Read more: https://www.drupal.org/docs/8/modules/webform/webform-cookbook/how-to-add-custom-validation-to-a-webform-element
  if ($element['#webform_id'] === 'efecte_id_element_id') {
    $element['#element_validate'][] = array(
      'Drupal\hy_esb\Validate\ValidateEfecteId',
      'validate'
    );
  }
}
