---
- hosts: all
  become: yes

  pre_tasks:
    - include_vars: "RedHat.yml"
    - import_tasks: tasks/init-redhat.yml
    - import_tasks: tasks/load-secrets.yml
      tags: [ always ]

  tasks:
    - name: Install extra packages
      package: name="{{ item }}" state=installed
      with_items: "{{extra_packages | list}}"

  roles:
    - { role: geerlingguy.repo-remi,      tags: [ 'repo' ] }
    - { role: geerlingguy.repo-epel,      tags: [ 'repo' ] }
    - { role: geerlingguy.git,            tags: [ 'git' ] }
    - { role: geerlingguy.mysql,          tags: [ 'mysql' ] }
    - { role: geerlingguy.php-versions,   tags: [ 'php' ] }
    - { role: geerlingguy.php,            tags: [ 'php' ] }
    - { role: geerlingguy.php-mysql,      tags: [ 'php' ] }
    - { role: geerlingguy.php-pecl,       tags: [ 'php' ] }
    - { role: geerlingguy.composer,       tags: [ 'composer' ] }
    - { role: geerlingguy.drush,          tags: [ 'drush' ] }
    - { role: jdauphant.nginx,            tags: [ 'nginx' ] }

  post_tasks:
    - template:
        src: settings.local.php.j2
        dest: "{{ projects.default.root }}/shared/settings.local.php"
